// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxXl4Rrk_XezEn-YVlKtVDEk0xwRa7HA',
    appId: '1:568300570141:web:e149a556d436965c1868f4',
    messagingSenderId: '568300570141',
    projectId: 'flashsale-52932',
    authDomain: 'flashsale-52932.firebaseapp.com',
    storageBucket: 'flashsale-52932.firebasestorage.app',
    measurementId: 'G-MKNHBQLW4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiwq6H6KOMavOEYk3om8pPnUk4A_yHGw',
    appId: '1:568300570141:android:f837edb4ccd080961868f4',
    messagingSenderId: '568300570141',
    projectId: 'flashsale-52932',
    storageBucket: 'flashsale-52932.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSsWVE205MyMK3lSMB8eLLXiu7wz2yYMU',
    appId: '1:568300570141:ios:d005aea68c519cff1868f4',
    messagingSenderId: '568300570141',
    projectId: 'flashsale-52932',
    storageBucket: 'flashsale-52932.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSsWVE205MyMK3lSMB8eLLXiu7wz2yYMU',
    appId: '1:568300570141:ios:d005aea68c519cff1868f4',
    messagingSenderId: '568300570141',
    projectId: 'flashsale-52932',
    storageBucket: 'flashsale-52932.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxXl4Rrk_XezEn-YVlKtVDEk0xwRa7HA',
    appId: '1:568300570141:web:7a7d9a9a5bf66d641868f4',
    messagingSenderId: '568300570141',
    projectId: 'flashsale-52932',
    authDomain: 'flashsale-52932.firebaseapp.com',
    storageBucket: 'flashsale-52932.firebasestorage.app',
    measurementId: 'G-509P0WM4QP',
  );

}